/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as DocsArchitectureRouteImport } from './routes/docs/architecture'
import { Route as DocsExtensionsRouteImport } from './routes/docs/extensions'
import { Route as DocsImageUploadRouteImport } from './routes/docs/image-upload'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsPublishingRouteImport } from './routes/docs/publishing'
import { Route as DocsReactRouteImport } from './routes/docs/react'
import { Route as DocsSerializationRouteImport } from './routes/docs/serialization'
import { Route as DocsSvelteRouteImport } from './routes/docs/svelte'
import { Route as DocsVueRouteImport } from './routes/docs/vue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsExtensionsRoute = DocsExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsImageUploadRoute = DocsImageUploadRouteImport.update({
  id: '/image-upload',
  path: '/image-upload',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPublishingRoute = DocsPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsReactRoute = DocsReactRouteImport.update({
  id: '/react',
  path: '/react',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSerializationRoute = DocsSerializationRouteImport.update({
  id: '/serialization',
  path: '/serialization',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSvelteRoute = DocsSvelteRouteImport.update({
  id: '/svelte',
  path: '/svelte',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsVueRoute = DocsVueRouteImport.update({
  id: '/vue',
  path: '/vue',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/extensions': typeof DocsExtensionsRoute
  '/docs/image-upload': typeof DocsImageUploadRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/publishing': typeof DocsPublishingRoute
  '/docs/react': typeof DocsReactRoute
  '/docs/serialization': typeof DocsSerializationRoute
  '/docs/svelte': typeof DocsSvelteRoute
  '/docs/vue': typeof DocsVueRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playground': typeof PlaygroundRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/extensions': typeof DocsExtensionsRoute
  '/docs/image-upload': typeof DocsImageUploadRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/publishing': typeof DocsPublishingRoute
  '/docs/react': typeof DocsReactRoute
  '/docs/serialization': typeof DocsSerializationRoute
  '/docs/svelte': typeof DocsSvelteRoute
  '/docs/vue': typeof DocsVueRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/extensions': typeof DocsExtensionsRoute
  '/docs/image-upload': typeof DocsImageUploadRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/publishing': typeof DocsPublishingRoute
  '/docs/react': typeof DocsReactRoute
  '/docs/serialization': typeof DocsSerializationRoute
  '/docs/svelte': typeof DocsSvelteRoute
  '/docs/vue': typeof DocsVueRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/playground'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/extensions'
    | '/docs/image-upload'
    | '/docs/installation'
    | '/docs/publishing'
    | '/docs/react'
    | '/docs/serialization'
    | '/docs/svelte'
    | '/docs/vue'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/playground'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/extensions'
    | '/docs/image-upload'
    | '/docs/installation'
    | '/docs/publishing'
    | '/docs/react'
    | '/docs/serialization'
    | '/docs/svelte'
    | '/docs/vue'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/playground'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/extensions'
    | '/docs/image-upload'
    | '/docs/installation'
    | '/docs/publishing'
    | '/docs/react'
    | '/docs/serialization'
    | '/docs/svelte'
    | '/docs/vue'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/extensions': {
      id: '/docs/extensions'
      path: '/extensions'
      fullPath: '/docs/extensions'
      preLoaderRoute: typeof DocsExtensionsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/image-upload': {
      id: '/docs/image-upload'
      path: '/image-upload'
      fullPath: '/docs/image-upload'
      preLoaderRoute: typeof DocsImageUploadRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/publishing': {
      id: '/docs/publishing'
      path: '/publishing'
      fullPath: '/docs/publishing'
      preLoaderRoute: typeof DocsPublishingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/react': {
      id: '/docs/react'
      path: '/react'
      fullPath: '/docs/react'
      preLoaderRoute: typeof DocsReactRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/serialization': {
      id: '/docs/serialization'
      path: '/serialization'
      fullPath: '/docs/serialization'
      preLoaderRoute: typeof DocsSerializationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/svelte': {
      id: '/docs/svelte'
      path: '/svelte'
      fullPath: '/docs/svelte'
      preLoaderRoute: typeof DocsSvelteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/vue': {
      id: '/docs/vue'
      path: '/vue'
      fullPath: '/docs/vue'
      preLoaderRoute: typeof DocsVueRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsExtensionsRoute: typeof DocsExtensionsRoute
  DocsImageUploadRoute: typeof DocsImageUploadRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsPublishingRoute: typeof DocsPublishingRoute
  DocsReactRoute: typeof DocsReactRoute
  DocsSerializationRoute: typeof DocsSerializationRoute
  DocsSvelteRoute: typeof DocsSvelteRoute
  DocsVueRoute: typeof DocsVueRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsExtensionsRoute: DocsExtensionsRoute,
  DocsImageUploadRoute: DocsImageUploadRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsPublishingRoute: DocsPublishingRoute,
  DocsReactRoute: DocsReactRoute,
  DocsSerializationRoute: DocsSerializationRoute,
  DocsSvelteRoute: DocsSvelteRoute,
  DocsVueRoute: DocsVueRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
